### ISSUE TITLE
Error adding in param

### ISSUE THREAD

**Issue by nataliecrowe060** [nataliecrowe060/Methane-NCrowe#4]
Hey Ben, me and Leeya both are unsure of how to add strat data without getting an error. Any idea what's wrong?
results<- fetchvars(core, 1745:2100, c(EMISSIONS_CH4(),  CONCENTRATIONS_CH4(), LIFETIME_STRAT()))
@bpbond @leeyap

**Comment by bpbond** [comment]
Hi Natalie, without seeing the error I would guess that the emissions and concentrations params both require dates, but the lifetime parameter can't have a date attached. So you'll probably need to do two separate `fetchvars` calls?

**Comment by leeyap** [comment]
Even with a date of "NA," we were getting this error:

```
Error in sendmessage(core, GETDATA(), v, dates, NA, "") : 
sendmessage: msg: Assertion failed: Unknown model datum: Tsoil
func: sendMessage
file: core.cpp
ffile:	core.cpp

line: 731
```
For both "Tsoil" and "Tstrat"

(Natalie, a parameter that doesn't change with time would have a `fetchvars()` date of `NA`)

**Comment by bpbond** [comment]
Hmm. So to reproduce this, I should (1) create a core and then (2) `fetchvars` LIFETIME_STRAT()?

**Comment by nataliecrowe060** [comment]
this is all the code I have up until then besides 'library' stuff: 
ini_file <- system.file("input/hector_ssp245.ini", package = "hector")
core <- newcore(ini_file)
run(core)
results<- fetchvars(core, 1745:2100, c(EMISSIONS_CH4(),                              CONCENTRATIONS_CH4(), LIFETIME_STRAT()))

**Comment by bpbond** [comment]
@nataliecrowe060 @leeyap I got a chance to try this out and...yep, errors. Natalie, welcome to 

# CUTTING EDGE SCIENCE WHERE THINGS BREAK 🤣 

It looks to me like we have a bug 🐛 and Natalie has found it. I will try to fix and open a Hector PR. Actually, maybe we can all look at it together later today.

**Comment by nataliecrowe060** [comment]
That's good with me!

**Comment by bpbond** [comment]
Interesting — see the linked PR. Those lifetime parameters were present in the R package but not linked to the model core; but this ALSO exposed a bug deep in the model internals. So, cheers 😄
