### ISSUE TITLE
Error using 'value' instead of set number

### ISSUE THREAD

**Issue by nataliecrowe060** [nataliecrowe060/Methane-NCrowe#7]
`x<-default %>%
  select(value)
ch4_low <- x * (1 - 0.2)
ch4_high <- x * (1 + 0.2)
ch4_seq <- seq(ch4_low, ch4_high, 5)`
This line works up until the sequence, "Error in is.finite(if (is.character(from)) from <- as.numeric(from) else from) : 
default method not implemented for type 'list'"- although when checking ch4_low and high they come back as a single value.

**Comment by leeyap** [comment]
Did we resolve this earlier? Or do you still need help?
